### ISSUE TITLE
Cannot open the settings

### ISSUE THREAD

**Issue by doniks** [ubports/terminal-app#40] opened 2018-06-03 19:00 UTC
## Steps to reproduce ##

  1. Open app
  2. try to open the settings - little cog wheel at the top right 

## Expected result ##

Settings open 

## Current result ##

Nothing happens - seems not to react to touch 

## General information ##

  [ Let us know more about your device. ]

  - __OS version:__   16.04
  - __Channel:__     dev channel 
  - __Device:__       Nexus 7 (deb)
  - __App version:__  `dpkg --list | grep term : 0.8.2ubports+0~xenial201802222211015.2~1`

## Logfiles and additional informations ##

[application-legacy-ubuntu-terminal-app-1528049233955354.log](https://github.com/ubports/terminal-app/files/2066272/application-legacy-ubuntu-terminal-app-1528049233955354.log)

**Comment by Flohack74** [comment] 2018-06-03 19:07
Duplicate of https://github.com/ubports/ubuntu-touch/issues/633

**Closed by Flohack74** 2018-06-03 19:07 UTC
